### ISSUE TITLE
widget partially drawn off-screen

### ISSUE THREAD

**Issue by rtwfroody** [hotbso/xgs#1]
I just installed this, and the widget is partially off the screen. See attached image. My screen resolution is 2560x1440 if that helps. xgs.prf (which I did not do anything to manually) contains:
```
20 1080 0
```
![Cessna_172SP - 2019-07-11 9 16 06 PM](https://user-images.githubusercontent.com/3102687/61137952-62fa1500-a47b-11e9-95b2-8596ceffc0d1.png)

**Comment by rtwfroody** [comment]
Changing that 1080 number to 600 puts the widget somewhere in the middle left of the screen, which is fine for me.

**Comment by hotbso** [comment]
Hhm,
it looks like the coordinates for drawing are less than the screen resolution. Did you run in full screen or windowed? Single monitor? Any VR gear?
Can you pls. delete/rename the xgs.prf run again and send the Log.txt?

**Comment by rtwfroody** [comment]
Full screen, single monitor, no VR. Attached is the log file you asked for. The xgs.prf was created again exactly as mentioned above, with the same problem.
[Log.txt](https://github.com/hotbso/xgs/files/3388954/Log.txt)

**Comment by hotbso** [comment]
May be I found a solution. Do you have the plugin "DatarefTool" installed?
Then please look for the datarefs 
`sim/graphics/view/window_width` and `sim/graphics/view/window_height` .
According to the doc this should reflect the coordinate system's width/height rather than the screen dimensions.

**Comment by rtwfroody** [comment]
I installed DatarefTool, and this is what it shows:
![image](https://user-images.githubusercontent.com/3102687/61755579-25e02d80-ad6d-11e9-9b04-b43a410b70bd.png)

**Comment by hotbso** [comment]
Another user had a similar problems
https://forums.x-plane.org/index.php?/files/file/45734-landing-speed-plugin-xgs-reloaded/&page=4&tab=comments#comment-276709

Do you have the 'User Interface Size' above 100% as well?

![image](https://user-images.githubusercontent.com/37118725/61857307-2b03c080-aec4-11e9-88ee-27f00bb2c88b.png)

**Comment by rtwfroody** [comment]
Yes. UI size is set to 150%.
![screenshot - 2019-07-25 17 18 35](https://user-images.githubusercontent.com/3102687/61917103-573d3280-af00-11e9-99b3-c4ea47053815.png)

**Comment by hotbso** [comment]
Thanx a lot. Now I know where the problem comes from. Unfortunately X Plane's widget library is not really aware of scaled UIs and multi monitor setup.
I will think about that but in any case it will be a significant rewrite of my code. So don't expect it too soon.

**Comment by hotbso** [comment]
It was simpler than I thought.
Please try out this beta after deleting/renaming xgs.prf with UI scale 150%.
[xgs-3.32b1.zip](https://github.com/hotbso/xgs/files/3438272/xgs-3.32b1.zip

**Comment by rtwfroody** [comment]
That seems to fix it. The widget now shows up center left:
![Cessna_172SP - 2019-08-01 14 45 02](https://user-images.githubusercontent.com/3102687/62329546-19458e80-b46b-11e9-85c5-ab7a54f81c99.png)
