### ISSUE TITLE
Question: VS and G

### ISSUE THREAD

**Issue by zodiac1214** [hotbso/xgs#3]
It looks like we are using the G/VS before touch down? 
say touchdown is at T1, we pick up G/VS from T0? is that right?

also
`static void update_landing_result()
{
    int changed = 0;
    if (landing_vspeed > last_vspeed) {
        landing_vspeed = last_vspeed;
        changed = 1;
    }
    if (landing_G < lastG) {
        landing_G = lastG;
        changed = 1;
    }
    if (changed || landMsg[0][0]) {
        int w = print_landing_message();
		if (w > window_width) {
			window_width = w;
            force_widget_visible (window_width);
			XPSetWidgetGeometry(main_widget, win_pos_x, win_pos_y,
                    win_pos_x + window_width, win_pos_y - WINDOW_HEIGHT);
		}
	}
}`

what if last_vspeed is lower than previously recorded but last G is lower? now we have VS from one timestamp and G from another? Should it be G/VS at touchdown point? i am not sure if i am wrong here or it was done intentionally for a reason. Like why we need to keep updating this if we know the touch down point? The landing G/VS should be what is at touchdown point?

**Comment by hotbso** [comment]
No and yes. Look what happens during and after touchdown:
tire deflection, strut compression come in while aerodynamic lift diminishes or even collapses.

In that phase vy goes down while g goes up. So normally you have max vy at around touchdown while max g is more at the end of the strut compression phase.

So depending of the ground/aerodynamics dynamics vy can still go up after touchdown.
Image that you come in extremely shallow scratching the runway meaning vy == 0. Then cut power. The struts compress and you have vy >0 after touchdown.
