### ISSUE TITLE
Howto Windows Compile MGW64

### ISSUE THREAD

**Issue by rwellinger** [hotbso/xgs#6]
I'm not able to build the plugin for windows. There library missing. I used the zlib and iconv from orginal lib and distribute to /usr/local ... but still not working... any idea? Problem I have is ... he can't link the library. (Not found it)

**Comment by hotbso** [comment]
Trying to reverse engineer what I have installed (it changed several times over the over the years):
It looks like I work now in the mingw64 environment that comes with git for Windows. This contains all the libraries.
![Screenshot 2024-01-14 153255](https://github.com/hotbso/xgs/assets/37118725/21216210-8405-43eb-97c1-d4cba40dc041)
